### PR TITLE
Add caOption ("auto") (2)

### PR DESCRIPTION
**Pull request by jasp00**
These commits restore caOption and add automatic signing, but it is restricted to selected schemes (e.g. "file:").

### CODE REVIEW

**Comment by mozkeeler** [comment]
@jasp00, thanks for making a smaller PR. For this particular feature, I'd appreciate some background on what the use-cases are. Is this expected to be called from other add-ons? Is it that useful to just take the first certificate getUserCerts returns and use it without asking the user?

**Comment by jasp00** [comment]
Automatic signatures may be useful in add-ons. They are useful in XUL applications that set the preference "When a server requests my personal certificate: Select one automatically" to establish connections. Generally, there is only one valid certificate, specially when the CA is specified. If there were more than one valid certificate, anyone should be fine.
The process also avoids asking for the same password that was used to establish the connection or to sign a previous message. Introducing the password just once is easier for the user.

**Comment by gamringer** [comment]
So happy to see this PR. I was about to start working on adding this functionality myself.

My requirements involves precisely that for any given CA, there should only be 1 valid certificate, so having automatic signature if only 1 is available fits nicely.

**Comment by mozkeeler** [comment]
@jasp00, I appreciate you taking the time to make and explain this PR, but I don't think this is a direction I'm interested in taking signTextJS. The goal of this project is to provide a stop-gap measure for users while sites migrate away from window.crypto.signText. These changes aren't sufficiently in line with that goal as they extend the add-on to be more than that. Also, I don't have much time or interest in maintaining support for this add-on. Making changes potentially increases these maintenance costs, and I'd like to avoid that. However, as this code is licensed under a fairly permissive license, you're welcome to fork it and make any changes you like. I imagine this isn't the resolution you were hoping for, but hopefully you still have a reasonable path forward.

**Pull request closed without merging**
